### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [shlomiLan/tvsort_sl#106]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.1.12. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary tvsort-sl -w /tmp/ext tvsort-sl==1.1.12
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting tvsort-sl==1.1.12
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/bd8/fdda8c54db4ff/tvsort_sl-1.1.12.tar.gz (6.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-iico51za/tvsort-sl/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-iico51za/tvsort-sl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-iico51za/tvsort-sl/pip-egg-info
         cwd: /tmp/pip-wheel-iico51za/tvsort-sl/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-iico51za/tvsort-sl/setup.py", line 9, in <module>
        long_description=open('readme.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by shlomiLan** [comment]
Hey, 

Thanks for your contribution.
I have merged your PR, but still see `warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md`. in the Travis logs.

doesn't it conflict with my `MANIFAST` file?

**Comment by thatch** [comment]
That message is doing a case-sensitive check.  Your sdist should have a file called "readme.md" now included, but the warning will still print because its not what setuptools considers the "standard" casing.

**Comment by thatch** [comment]
If you'd like to silence that, you'll need to rename your readme to be "README.md" instead.

**Comment by shlomiLan** [comment]
Changed the file name to `README.md`
