### ISSUE TITLE
Documentation for building from source and running

### ISSUE THREAD

**Issue by tsikerdekis** [shlomiLan/tvsort_sl#30]
I used
`pip3 install -e .`
and everything install fine (although not sure that any of the dependencies are installed).

I am not sure what command to run next though. I tried the following but got back an error:
```
python3 -m tvsort_sl.app
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/m/tvsort_sl/tvsort_sl/app.py", line 19
    settings: Dict[str, Union[str, bool]] = dict(PROJECT_NAME=project_name, LOG_PATH=os.path.join(BASE_DIR, 'logs'))
            ^
SyntaxError: invalid syntax
```

**Comment by shlomiLan** [comment]
**Install:**
```
pip install virtualenv
virtualenv venv
source ./venv/bin/activate
pip install -r dev.txt
mkdir logs
```

Update `local.yml` in `tvsort_sl/tvsort_sl/settings`

**Use:**
```
cd tvsort_sl
python -m tvsort_sl.app
```

Let me know how it goes :-)
