### ISSUE TITLE
README.rst not found when installing through pip

### ISSUE THREAD

**Issue by AntStephenson** [shlomiLan/tvsort_sl#51]
Whilst trying to install tvsort_sl via pip ~~in a container~~ both in a container and on OS X I'm getting an error:

```
Collecting tvsort_sl
  Downloading https://files.pythonhosted.org/packages/d9/ab/cf3d587762fa6d6455347f7b37944b0f6415df5e4ff830e04c42485a6f1b/tvsort_sl-1.0.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l30rrq_x/tvsort-sl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l30rrq_x/tvsort-sl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-l30rrq_x/tvsort-sl/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l30rrq_x/tvsort-sl/setup.py", line 12, in <module>
        long_description=open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I guess it has something to do with the following (which doesn't exist since ~ Dec 2018):
https://github.com/shlomiLan/tvsort_sl/blob/ec7d8e46467cda364f58ec0346986cfd406f8fc4/setup.py#L9

**Comment by shlomiLan** [comment]
Version `1.0.3` was released and slove this issue.

**Comment by AntStephenson** [comment]
Thank you!

**Comment by shlomiLan** [comment]
Please let me know if you found it helpful :-)
